- .licenserc.yaml
- charms/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/k8s/lib/charms/operator_libs_linux/v2/snap.py
- charms/k8s/pyproject.toml
- charms/k8s/tests/unit/test_k8sd_api_manager.py
- charms/k8s/tox.ini
Refactor `K8sAPIManager` as a charm library and include Snap management libraries.
As a preemptive approach to reduce code duplication between the `k8s` and `k8s-worker` charms, this PR introduces the `K8sAPIManager` as a charm library, which can be shared among them.
- Added `K8sAPIManager` charm library.
- Added `snap` library.
- New tests for the `K8sAPIManager` library.
> Refactor K8sAPIManager and Snap Libraries as shared libraries

- charms/k8s/charmcraft.yaml
- charms/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/k8s/lxd-profile.yaml
- charms/k8s/pyproject.toml
- charms/k8s/src/charm.py
- charms/k8s/tests/unit/test_base.py
- charms/k8s/tests/unit/test_k8sd_api_manager.py
Generate a first version of the `k8s-operator` charm.
This pull request introduces an initial version of the `k8s-operator`, which has the option to bootstrap and deploy a one-node cluster. This is a stepping stone for future work that has to be done in the charm.
- Refactored `on_install` handler
- Refactored `update_status` handler
- Bumped `k8s_api_manager` patch.
- Added Pydantic models and validators for the ClusterStatus endpoint.
- Added methods for checking k8sd cluster state
> Bootstrap k8s-operator

- charms/k8s/charmcraft.yaml
- charms/k8s/requirements.txt
- charms/k8s/src/charm.py
- charms/k8s/tests/unit/test_base.py
Refactor the charm's business logic to follow the reconcile pattern.
Due to the unstable and unpredictable behavior resulting from using `event.defer()` in the charm, it is recommended to fallback to a more robust mechanism. This pull request introduces a refactor in the charm's business logic, aligning it with the reconcile pattern. This change involves the usage of two libraries: [charm-lib-contextual-status](https://github.com/charmed-kubernetes/charm-lib-contextual-status) and [charm-lib-reconciler](https://github.com/charmed-kubernetes/charm-lib-reconciler).
- Modified `update-status` handler.
- Added `reconciler` handler.
> Implement  `reconcile` pattern

- charms/k8s/charmcraft.yaml
- charms/k8s/metadata.yaml
- charms/k8s/src/charm.py
- tests/integration/conftest.py
Implement the Join Cluster process for `k8s` charm units.
This pull request introduces the implementation for joining multiple control plane units into the cluster via the `cluster` peer relation. This relation utilizes Juju secrets for distributing the cluster join tokens over the relation data.
- Handlers have been added for the cluster relation (`create_cluster_tokens` and `join_cluster`).
> Implement `k8s` clustering

- .github/workflows/publish-k8s-worker.yaml
- .github/workflows/publish-k8s.yaml
Fix Path to k8s and k8s-worker charm.
depends on
*  https://github.com/canonical/charming-actions/pull/132
> Adjust publish to edge paths for k8s and k8s-worker

- charms/worker/k8s/src/charm.py
- tests/integration/test_k8s.py
Applicable spec: https://warthogs.atlassian.net/browse/KU-327
Generate kubeconfig file in `/root/.kube/config` on the control-plane nodes
In order for admins to access the cluster with tools they are familiar with, the charm should copy out the admin kubeconfig out to `/root/.kube/config
Adds a new method to the reconcile routine
Reorder all the reconciler routines in the order they are called
> Render kubeconfig in root ${HOME}/.kube/config

- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/lib/charms/grafana_agent/v0/cos_agent.py
- charms/worker/k8s/requirements.txt
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/cos_integration.py
- charms/worker/k8s/src/token_distributor.py
- charms/worker/k8s/templates/cos_roles.yaml
- charms/worker/k8s/templates/ksm.yaml
Implement the `cos-agent` integration for `k8s` and `k8s-worker` charms.
This pull request introduces an implementation for integrating our charms with the Canonical Observability Stack. In this first version, we demonstrate the capabilities of sending scrape jobs to Prometheus over relation data for the following Kubernetes components:
1. **Kubernetes Control Plane (`k8s`):**
- Kube API Server
- Kube Controller Manager
- Kube Proxy
- Kube Scheduler
- Kubelet
- cAdvisor
- Probes
- Kube State Metrics
2. **Kubernetes Worker (`k8s-worker`):**
- Kubelet
- cAdvisor
- Probes
- Kube Proxy
This initial version of the integration relies on manual testing. Integration tests will be introduced in future PRs.
- Introduced a new `TokenDistributor` module to generalize token distribution for the …
> Implement `cos-agent` integration

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/token_distributor.py
- tests/integration/conftest.py
* Make the secret-id transfer complete over unit data relation so that workers non-leaders can read the secret-id
k8s-workers that are non leaders couldn't read from the app relation data. Therefore, we must use the unit data for transferring the secret-ids
None
Move the token request into token_distrobution.py as well.
None
> Handle using a cluster token to join only once

- charms/worker/k8s/scripts/update_dashboards.py
- charms/worker/k8s/src/grafana_dashboards/apiserver.json
- charms/worker/k8s/src/grafana_dashboards/cluster-total.json
- charms/worker/k8s/src/grafana_dashboards/controller-manager.json
- charms/worker/k8s/src/grafana_dashboards/k8s-resources-cluster.json
- charms/worker/k8s/src/grafana_dashboards/k8s-resources-multicluster.json
- charms/worker/k8s/src/grafana_dashboards/k8s-resources-namespace.json
- charms/worker/k8s/src/grafana_dashboards/k8s-resources-node.json
- charms/worker/k8s/src/grafana_dashboards/k8s-resources-pod.json
- charms/worker/k8s/src/grafana_dashboards/k8s-resources-workload.json
- charms/worker/k8s/src/grafana_dashboards/k8s-resources-workloads-namespace.json
- charms/worker/k8s/src/grafana_dashboards/kubelet.json
- charms/worker/k8s/src/grafana_dashboards/namespace-by-pod.json
- charms/worker/k8s/src/grafana_dashboards/namespace-by-workload.json
- charms/worker/k8s/src/grafana_dashboards/persistentvolumesusage.json
- charms/worker/k8s/src/grafana_dashboards/pod-total.json
- charms/worker/k8s/src/grafana_dashboards/proxy.json
- charms/worker/k8s/src/grafana_dashboards/scheduler.json
- charms/worker/k8s/src/grafana_dashboards/workload-total.json
- charms/worker/k8s/src/token_distributor.py
- charms/worker/k8s/tox.ini
Implement the Grafana Dashboards integration via `cos-agent` for `k8s` and `k8s-worker` charms.
This pull request introduces an implementation for sending dashboards to Grafana via relation data.
This version of the integration relies on manual testing. Integration tests will be introduced in future PRs.
- Introduced a `scripts` folder, which holds the update script for pulling the dashboards from the upstream repository. It also ensures that the dashboards are in the correct format.
- Added a new environment for updating the dashboards via `tox`.
> Add Grafana Dashboards integration

- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/requirements.txt
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/test_base.py
- tests/integration/test_k8s.py
Applicable spec: https://warthogs.atlassian.net/browse/KU-325
Allows for charm config to label worker and control-plane nodes
Allows a juju administrator to specify certain node labels so that dependent workloads can run on properly labeled kubelets.  Will need access to the kubeconfig via https://github.com/canonical/k8s-operator/pull/22
N/A
N/A
Addition of the node-label library 
* https://github.com/charmed-kubernetes/layer-kubernetes-node-base/pull/11
> Add node-labeling charm config using the LabelMaker library

- tox.ini
Run integration tests with juju-crashdump so that CI failures can be evaluated
> Chore: Crashdump as root with the journalctl from k8s snap

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
Refactor ClusterStatus Pydantic Model
The ClusterStatus response DTO was changed in a recent `k8s-snap` PR https://github.com/canonical/k8s-snap/pull/179. Therefore, when the charm tries to deserialize the response, it fails to retrieve the cluster status. This pull request refactors the Pydantic model to address this issue.
> Refactor ClusterStatus Model

- CONTRIBUTING.md
- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/src/charm.py
- tests/integration/test_k8s.py
Resolves an issue where the charm didn't remove labels it had added via config.
Removes unnecessary management of the node role label
in order to use `ops.StoredState`, the `ops.Object` in `LabelMaker` must have a lifetime equal to the `ops.CharmBase` otherwise the framework cannot run it's `on_commit` handler to actually save the state. 
This PR  changes `LabelMaker(...)` to be owned by the Charm itself as an attribute (`self._labeler`) rather than constructing the labeler in the `apply_node_labels` handler
> the snaps set the node-role labels, the charm only now worries about custom labels

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/test_base.py
- charms/worker/k8s/tests/unit/test_k8sd_api_manager.py
- tox.ini
Include UserFacingClusterConfig
The UserFacingClusterConfig response DTO was included in a recent `k8s-snap` PR https://github.com/canonical/k8s-snap/pull/184. This pull request synchronize the API payloads.
> Include `UserFacingClusterConfig`

- .github/workflows/integration_test.yaml
- CONTRIBUTING.md
- tests/integration/conftest.py
- tests/integration/cos_substrate.py
- tests/integration/data/cos-offers-overlay.yaml
- tests/integration/data/microk8s.profile
- tests/integration/grafana.py
- tests/integration/helpers.py
- tests/integration/prometheus.py
- tests/integration/test-bundle.yaml
- tests/integration/test_k8s.py
- tox.ini
Add a `COS` substrate fixture to ease COS integration.
We usually test COS integration using the same K8s as the substrate for the COS stack. However, we would want to mimic the real-world environment. This pull request replicates a COS instance related to the K8s cluster using Cross-Model Integration.
- Added a Grafana module to verify the Grafana integration.
- Added a Prometheus module which verifies the Prometheus integration, querying the cluster for the known metrics jobs.
- Added a COS substrate module implementation using LXD. It creates a separate network and instance, completely independent from the cluster itself (the cluster is using MicroK8s as the K8s substrate).
- Added tests for Grafana and Prometheus.
> [COS] Add `COS` substrate fixture

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/test_base.py
- tests/integration/test-bundle.yaml
Expose ports to the kubernetes api endpoint service on control-plane units, and expose those apps on public clouds during testing
Without this, security groups will prevent using kubernetes clients from accessing the API endpoints outside the cloud
> Expose ports and apps when running in public clouds

- charms/worker/k8s/scripts/update_alert_rules.py
- charms/worker/k8s/scripts/update_dashboards.py
- charms/worker/k8s/tests/unit/__init__.py
- charms/worker/k8s/tests/unit/test_base.py
- charms/worker/k8s/tests/unit/test_k8sd_api_manager.py
- tests/integration/conftest.py
- tests/integration/cos_substrate.py
- tests/integration/grafana.py
- tests/integration/helpers.py
- tests/integration/prometheus.py
- tests/integration/test_k8s.py
Paired with https://github.com/canonical/k8s-operator/pull/50, this handled other linting issues within the repo
> [COS] Push deeper linting into the repo for integration and unit testing

- .licenserc.yaml
This charm maintains the `k8s` charm library under `charm/worker/k8s/lib/charms/k8s` so we should license check those files.  But we want to ignore any other charm license headers bc we can't do anything about them
> include license check on k8s charm library but ignore downloaded library

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/token_distributor.py
- charms/worker/k8s/tests/unit/test_k8sd_api_manager.py
- tests/integration/data/test-bundle-etcd.yaml
- tests/integration/data/test-bundle.yaml
- tests/integration/test_etcd.py
- tox.ini
Summary:
Pydantic models do not need to populate fields that can be sent to the server as nil.  It's best to omit them to prevent unnecessary server-side checking. 
Changes:
* Change the Models to default all fields to `None`
* Adjust the linter to check the `...k8s/lib/charms/k8s` path
* Adjust the tests to set constraints on the machines for CI (in the event they are not lxd -- these constraints are applied)
* Add integration test to confirm we're using external datastore
* Wrap tokens in a `SecretStr` to prevent the secret from leaking in logs
> Ensure all bootstrap arguments are nil unless otherwise specified

- .github/workflows/publish-charms.yaml
When publishing the charms to latest/edge, tag the repo with multiple tags, one for each charm revision.
> Handle tagging with different prefix during charm publish

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/test_base.py
- tests/integration/test_etcd.py
Since the charm reconcile loops runs the same execution steps over and over, providing meaning descriptions of those stages is important.  These changes better describe the stages the charm is stepping through -- not just the early stages
* Many of the MaintenanceStatus messages were update to show that they are repeating the same stage of configuration, which may already be applied
* Improved the worker's status when it's blocked by not being related to the k8s control-plane application
> Improve the juju unit status

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/charm.py
- tests/integration/data/test-bundle.yaml
Introduces config `service-cidr` and `register-with-taints`.  I considered also introducing `cidr` -- but may wait and leave it default for now in case we later introduce CNI relation
Pairs with snap changes
* https://github.com/canonical/k8s-snap/pull/218
> Configuration for service-cidr and control-plane-taints

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/requirements.txt
- charms/worker/k8s/src/charm.py
- tests/integration/test_etcd.py
Satisfies the `external-cloud-provider` relation - the k8s charms can bootstrap using the `external` cloud-provider
While this isn't enough for the other cloud-provider charms to get credentials from the cluster -- this is enough to complete half the relation and indicate that the cloud-provider is externally available. 
--- Note ---
`aws-cloud-provider` requires the nodes to use fqdn rather than the bare hostname in the node names.  It's best in this case to just always use the fqdn when running on aws
> Support the external-cloud-provider on bootstrap of k8s

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/test_base.py
- charms/worker/k8s/tests/unit/test_k8sd_api_manager.py
- tests/integration/test_etcd.py
With https://github.com/canonical/k8s-snap/pull/334 the snap allows to configure the external datastore on runtime. This allows for changes of the etcd configuration after the cluster is bootstrapped. 
The snap only performs steps (restarting services etc.) if a configuration changed. Hence, we can just send the current datastore configuration of the charm to the endpoint on every event. If there is no change, nothing happens.
* Add `UserFacingDatastoreConfig` type as defined in the `k8s-snap` API
* Update `Datastore` status type
* Add `datastore` to the `UpdateClusterConfigRequest`
* Add new reconcile step `ensure_cluster_config`
> Integrate runtime updates for etcd

- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/snap.py
- charms/worker/k8s/templates/snap_installation.yaml
- charms/worker/k8s/tests/unit/test_base.py
- charms/worker/k8s/tests/unit/test_snap.py
Rather than encode the snap revisions into the charm code directly, include a file installed by the charm to specify the revision or channel of the snap.  Each charm branch may adjust this file's contents in order to either install by channel or by revision. 
* The same snap-installation.yaml will be available for both the built `k8s` and `k8s-worker` charm. 
* the revision file is arch aware to support different snap revisions based on the architecture for which its built
* later CI actions can be used to automate the update of the revisions
* the charm can be influenced via adjustments to this file to allow for arbitrary snap revision installation
> Replace snap channel config for hard coded revision config

- .github/workflows/build-charm.yaml
- charms/worker/k8s/requirements.txt
This pull request introduces a caching mechanism for charms. If there are no changes in the source of the charm or its dependencies, the workflow restores the cached charms. This reduces integration test times by around 80%. This is particularly useful when tweaking the testing suite or other files that are not dependent on the charm sources.
> Cache Charm Builds

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/test_base.py
Use the same `_configure_datastore(...)` method to configure datastore properties
> Safely configure datastore request in the same method

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/templates/snap_installation.yaml
Attempts to lengthen the amount of time that a leaving node exists to give time to the lead control-plane charm time to remove the unit
* revoke tokens only when `k8s-cluster` and `cluster` relations experience a RelationDepartedEvent
* detect departing unit and elect for removal
* `update_status` event now checks if the node itself is ready with kubectl
* `last_gasp` now requires the node to be reported not in a `Ready` at least 3 times before ending the delay
> Improve node removal by validating departed|broken relations

- test_requirements.txt
Unpin github version of pytest-operator with the release of pytest-operator 0.35.0
> unpin pytest operator

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/snap.py
- charms/worker/k8s/src/token_distributor.py
- charms/worker/k8s/tests/unit/test_base.py
- charms/worker/k8s/tests/unit/test_snap.py
- charms/worker/k8s/tests/unit/test_token_distributor.py
- tests/integration/test_k8s.py
Address #74 and  #75 
Prevent reclustering errors after removing all control-plane units without destroying the control-plane application itself.
* If all control-plane units are removed  --  a new one would constitute a new cluster
Therefore existing workers should not try to cluster with the new control-plane units.
* on API join and the node is already clustered, ignore error response
* on API remove and the node is not joined, ignore error response
* dying nodes never reconcile (any juju event will be handled with reconciler)
* synchronize cluster relation using a unique `cluster-name` from the leader control-plane
* synchronize cluster relation using a response from units on the  `joined` field
* ignore errors while removing tokens when:
1) node is removing itself
2) token may not …
> Cluster a node only once, block worker units which are asked to recluster with a new control-plane

- .github/workflows/auto-update-libs-k8s-worker.yaml
- .github/workflows/charm-analysis.yaml
- .github/workflows/comment.yaml
- .github/workflows/integration_test.yaml
- .github/workflows/load_test.yaml
- .github/workflows/promote-charms.yaml
- .github/workflows/publish-charms.yaml
- tests/integration/conftest.py
- tests/integration/test_etcd.py
Pinning operator-workflows to https://github.com/canonical/operator-workflows/commit/08c5a65a0bc4696164b4f85a29a9ccbd830d10d8
Not only does this pin the workflows but it fixes a race condition where sometimes the CI fails when it sees k8s-worker in a blocked state.  That's not necessarily an error -- blocked state is just fine.  It's really error state we should be worried about.
> pin operator-workflow to a commit

- charms/worker/k8s/src/snap.py
- charms/worker/k8s/templates/snap_installation.yaml
- charms/worker/k8s/tests/unit/test_snap.py
Pins the snap revision rather than using a snap channel
Doing so, I discovered an issue with the logic within the snap library.  Every time you call `snap.ensure` it will refresh the snap, even if the snap revisions match.  This caused some of the services of k8s to be stopped, and never restarted. 
By checking the current revision against the target snap revision, we can prevent the charm from calling `snap refresh` over and over again
> Pin snap revision for amd64

- .github/workflows/update-snap-revision.py
- charms/worker/k8s/src/snap.py
- charms/worker/k8s/templates/snap_installation.yaml
Release 1.30 Update
Pinning amd64 revision to 313
Pinning arm64 revision to 314
Removes snap channel following
Enforces a snap hold forever
The CI job checks for new versions on `1.30-classic/stable` and updates when new stables are available
* this release branch will publish charms to 1.30/edge but using only 1.30-classic/stable snaps
> [Release 1.30] Snap Revision Update

- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
Resolves https://github.com/canonical/k8s-operator/issues/107
It seems that a bug in juju 3.1 prevents the k8s charm from deploying on any series (jammy or focal) because it mentions an unsupported series (noble)
The message from juju is cryptic (see issue) so to not confuse users, it seems most prudent to just update the minimum version of the charm to 3.3\
Will need to cherry-pick to main on merge
> `runs-on` noble requires at least juju3.3 and beyond

- charms/worker/k8s/src/charm.py
- tests/integration/conftest.py
Swap from `juju-info` relation to `cluster` relation when determining which address to bind for bootstrapping
> Prefer the cluster relation for bootstrap address rather than juju-info

- test_requirements.txt
Workaround for pylxd connections failing in CI due to https://github.com/psf/requests/issues/6707
> pin requests < 2.32

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/reschedule.py
- charms/worker/k8s/tests/unit/test_reschedule.py
- charms/worker/k8s/tox.ini
- tests/integration/conftest.py
Uses systemd to schedule an update-status hook under certain situations to complete node bootstrapping.
In some circumstances, the charm doesn't complete deployment by the time the last juju event hook fires.  Rather than using event.defer on the last hook event, this creates a reschedulable systemd call to `update-status` hook until the node is ready.
Resolves issue #90
> Use systemd to reschedule update-status hooks

- charms/worker/charmcraft.yaml
- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/certificates.py
- charms/worker/k8s/src/charm.py
- pyproject.toml
- test_requirements.txt
- tests/integration/conftest.py
- tests/integration/data/test-bundle-certificates.yaml
- tests/integration/test_certificates.py
This pull request adds support for external certificates for non-leader control planes and worker units.
A mechanism is required to allow the joining units to request their own certificates and pass them to the joining configuration object. In this pull request, joining units can request their required certificates over the TLSCertificatesv3 interface, which can be used with charms that implement this interface (e.g., new Vault or self-signed-certificates).
> Add Joining Certificates for non-leader Control Planes and Workers

- tests/integration/conftest.py
Applies workaround for testing cilium on AWS from [LP#2016905](https://bugs.launchpad.net/charm-cilium/+bug/2016905/comments/1)
Integration test attempts to determine which cloud the controller is on, in order to apply correct model configuration
> Address fan-network disabling on aws

- .github/workflows/build-charm.yaml
- .github/workflows/integration_test.yaml
- .github/workflows/publish-charms.yaml
The publishing charm action fails due to not being able to read a charmcraft yaml tuned for charmcraft 2.x.  This updates the publish-charm action to read the charmcraft channel version from a file in repo. 
a previous [action](https://github.com/canonical/k8s-operator/actions/runs/10291869467) no longer operates due to charmcraft promoting the snap 3.1.1 to its latest/stable channel.  
#137 fixed this by pinning the BUILD channel to 2.x/stable, but couldn't publish the built charm.
* juju has asked us to no longer use juju `3.3/stable` -- but rather `3/stable` snap
> Publish charms with a specific revision of charmcraft

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/tests/unit/test_k8sd_api_manager.py
With the advent of v2 microcluster, the ready endpoint moved from `/cluster/1.0/ready` to `/core/1.0/ready` because changing endpoints is a totally natural thing to do for run
* loop through available endpoints til we find one that doesn't `404`.  
* reraise any non-404 excptions
* raise a `K8sdConnectionError` if we run out of endpoints to try
> Handle various microcluster ready endpoints

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/token_distributor.py
- tests/integration/conftest.py
- tests/integration/grafana.py
- tests/integration/helpers.py
- tests/integration/prometheus.py
- tests/integration/test_k8s.py
* Incorporates testing lessons learned from #141 
* Addresses an issue where the lead control-plane unit was not allocated a cos-token, so it posted no metrics
* Adds the fixes to the COS tests found in #141 
* Gets the traefik url from an action on that charm rather than using the unit's public address
* Deploy a grafana-agent matching the series+arch of the primaries (k8s-worker and k8s)
* Wait for prometheus to be healthy for only 10 minutes before failing
* Adjust prometheus test to return the metrics for evaluation of which metrics are missing
> [COS] Adjustments to integration tests to more reliably test COS relations

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/requirements.txt
- charms/worker/k8s/scripts/update_alert_rules.py
- charms/worker/k8s/scripts/update_dashboards.py
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/containerd.py
- charms/worker/k8s/src/snap.py
- charms/worker/k8s/src/token_distributor.py
- charms/worker/k8s/tests/unit/test_containerd.py
- charms/worker/k8s/tests/unit/test_k8sd_api_manager.py
- charms/worker/k8s/tests/unit/test_reschedule.py
- charms/worker/k8s/tests/unit/test_snap.py
- pyproject.toml
- tox.ini
With more linting powers comes more linting issues
* resolve issues found pylint in its latest version 3.3.0
* includes https://github.com/canonical/k8s-operator/pull/148
> Chore: Fix pylint issues with new version of pylint

- charms/worker/k8s/charmcraft.yaml
Fix the example configuration to use `k8s` instead of `containerd`.
> Update `containerd_custom_registries` description

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/charm.py
Add a charm configuration option to enable the fine grained configuration of clusters using annotations.
The `k8s` snap allows the use of annotations as a mechanism to configure features built into the snap. For example, to configure VLAN BPF bypass in Cilium (as requested in #112), we can use the annotation `k8sd/v1alpha1/cilium/vlan-bpf-bypass` which passes the VLAN IDs to Cilium's configuration.
closes #112
> Add Annotations to Charm Configuration

- .github/workflows/integration_test.yaml
- tests/integration/conftest.py
Switches testing of lxd to use VMs rather than nested containers and a difficult to install lxd profile
* creates a new pytest option which is directed to use lxd-containers rather than lxd vms -- then defaults it off
* updated the conftest.py to instruct juju to start a `virt-type: virtual-machine` and disregard loading a lxd profile.
> Attempt to use lxd vms rather than containers

- charms/worker/k8s/lib/charms/grafana_agent/v0/cos_agent.py
- charms/worker/k8s/lib/charms/operator_libs_linux/v2/snap.py
Automated action to fetch latest version of charm libraries. The branch of this PR
will be wiped during the next check. Unless you really know what you're doing, you
most likely don't want to push any commits to this branch.
> Update charm libraries

- .github/workflows/integration_test.yaml
- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/src/charm.py
- test_requirements.txt
- tests/integration/conftest.py
- tests/integration/data/test-bundle-ceph.yaml
- tests/integration/test_ceph.py
- tox.ini
Enable Ceph CSI integration.
We're recommending ceph as the storage solution when using Canonical K8s as the backing cloud for `juju add-k8s`. This PR provides the integration needed by the `ceph-csi` subordinate charm.
Adds a new relation-changed observation for `ceph-k8s-info`.
> enable ceph-csi integration

- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/requirements.txt
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/cloud_integration.py
- charms/worker/k8s/src/kube_control.py
- charms/worker/k8s/src/protocols.py
- charms/worker/k8s/src/token_distributor.py
- charms/worker/k8s/tests/unit/test_cloud_integration.py
- pyproject.toml
Make use of https://github.com/charmed-kubernetes/interface-kube-control/pull/2 to support integration of the k8s operator with aws
* support publishing the ca-cert of the k8s endpoint over the kube-control relation
* support publishing the auth tokens over the kube-control relation via secrets
* integration k8s and k8s-worker with gcp, azure, and aws cloud integrators
* bootstraps with a unique cluster-name passed to the k8s-snap
> Integrate with cloud-provider and test with AWS

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/src/charm.py
Add options to the k8s charm to configure the gateway via charm configuration.
A user may want to overwrite the default configuration for gateway. This should be possible both - when bootstrapping a cluster and during runtime. Currently, there is only the option to enable or disable the feature.
* Add the gateway config to the cluster config map
> Add gateway charm options

- tests/integration/conftest.py
- tests/integration/data/test-bundle-ceph.yaml
- tests/integration/data/test_ceph/ceph-xfs-pvc.yaml
- tests/integration/data/test_ceph/pv-reader-pod.yaml
- tests/integration/data/test_ceph/pv-writer-pod.yaml
- tests/integration/helpers.py
- tests/integration/test_ceph.py
- tox.ini
We'll extend the Ceph storage class test to actually create a PVC and ensure that pods can read/write data from these volumes.
While at it, we're making some slight changes to the ceph bundle. At the moment, it deploys a single unit with two OSDs and node based replication (default). For this reason, the PGs are inactive and the rbd commands hang (and implicitly the Ceph provisioner). We'll fix this by using three units, each containing one OSD.
We're also updating the pytest command to include timestamps.
> Extend ceph sc tests

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/test_base.py
Applicable spec: KU-2118
Adds metric-server and dns-config
Allows a juju admin to adjust features deployed by the charm
None
Removed redundant charm.py method `_ensure_features()`
None
> Add charm config for metrics-server and dns-config

- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/config/extra_args.py
- charms/worker/k8s/src/events/update_status.py
- charms/worker/k8s/tests/unit/test_config_options.py
- tests/integration/data/test-bundle.yaml
- tests/integration/test_k8s.py
During bootstrap, control-plane node-join, and worker node join, apply extra arguments for kube services. 
* test that the `v=3` option set the options to `--v=3` for each kube service on each unit
* ensure that joined control-planes and joined workers use the same charm config arguments
> Adds ability to set extra args for kube services

- charms/worker/k8s/src/charm.py
The DNS config was not properly passed down to the update call which caused the DNS feature to always be disabled.
> fix: dns config name

- charms/worker/k8s/src/charm.py
Backport of dns config bug fix: https://github.com/canonical/k8s-operator/pull/189
> [Backport 1.31] Fix dns config name (#189)

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
This PR removes the unused `default-tls-secret` field from the `IngressConfig` (left over from [this commit](https://github.com/canonical/k8s-operator/pull/176/commits/7233a6db9e2418f8b321b31f25be11b5c1d2d416)).
> Remove unused tls field

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/src/charm.py
- tests/integration/conftest.py
Renames `annotations` to `cluster-annotations` in charm config.
> Rename annotations to cluster-annotations

- .github/workflows/integration_test.yaml
Kind of backs out #203, builds were queuing up due to a lack of builders, and our workflows require quite a few builders.
> Adjust workflow pinning again

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/literals.py
- charms/worker/k8s/src/upgrade.py
- charms/worker/k8s/tests/unit/test_token_distributor.py
- charms/worker/k8s/tests/unit/test_upgrade.py
Replace magic string in the codebase with constants.
To align with the best practices from other charms and improve the code maintainability, this pull request replaces the "magic strings" used in the code with constants.
> Replace Magic Strings with `literals.py` Constants

- charms/worker/charmcraft.yaml
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/config/extra_args.py
The control-plane charm already allows defining node taints. We'll add the same for worker nodes.
> Add worker bootstrap-node-taints setting

- .github/workflows/load_test.yaml
Applicable spec: KU-2129
Load-test runs need corrected charmcraft channel
> Load-Test: build with correct charmcraft

- charms/worker/k8s/src/charm.py
Enhance status visibility during cluster upgrades.  
To better surface the current state of the cluster upgrade, this pull request introduces an improvement for the `k8s` leader unit to track and report the upgrade status. This includes showing how many control plane and worker units are still pending upgrade in the unit status message.
```
Model        Controller      Cloud/Region         Version  SLA          Timestamp
k8s-cluster  lxd-controller  localhost/localhost  3.6.1    unsupported  14:53:30-05:00
App         Version  Status   Scale  Charm       Channel  Rev  Exposed  Message
k8s         1.31.3   waiting      2  k8s                    2  no       Upgrading 2 Worker units
k8s-worker  1.31.2   active       2  k8s-worker             0  no       Ready
Unit           Workload  Agent …
```
> Enhance Upgrade Status

- charms/worker/k8s/terraform/README.md
- charms/worker/k8s/terraform/main.tf
- charms/worker/k8s/terraform/outputs.tf
- charms/worker/k8s/terraform/variables.tf
- charms/worker/k8s/terraform/versions.tf
- charms/worker/terraform/README.md
- charms/worker/terraform/main.tf
- charms/worker/terraform/outputs.tf
- charms/worker/terraform/variables.tf
- charms/worker/terraform/versions.tf
Applicable spec: https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit?tab=t.0
Adds basic terraform modules for the k8s charms
Enable deploying canonical k8s with terraform
N/A
N/A
N/A
> inital pass at adding terraform for the k8s charms

- charms/worker/k8s/src/charm.py
Allow the `k8s` charm to integrate with multiple `k8s-worker` units.  
We have observed that the charm cannot integrate with multiple `k8s-worker` applications in a Juju model. To support this integration, we have added support for multiple relation endpoints in the integrations shared with the `k8s-worker` charm.
```
Model        Controller  Cloud/Region    Version  SLA          Timestamp
k8s-cluster  canosphere  vsphere/Boston  3.6.1    unsupported  08:50:44-05:00
App         Version  Status  Scale  Charm       Channel  Rev  Exposed  Message
k8s         1.31.2   active      2  k8s                    0  no       Ready
k8s-foo     1.31.2   active      1  k8s-worker             0  no       Ready
k8s-worker  1.31.2   active      2  k8s-worker             0  no       Ready
Unit …
```
> Allow `k8s` to integrate with multiple worker units

- .github/workflows/integration_test.yaml
- charms/worker/k8s/src/events/update_status.py
- charms/worker/k8s/src/inspector.py
- charms/worker/k8s/src/literals.py
- charms/worker/k8s/src/protocols.py
- charms/worker/k8s/src/upgrade.py
- charms/worker/k8s/tests/unit/test_upgrade.py
- tests/integration/conftest.py
- tests/integration/data/test-bundle-ceph.yaml
- tests/integration/data/test-bundle-etcd.yaml
- tests/integration/data/test-bundle.yaml
- tests/integration/helpers.py
- tests/integration/test_ceph.py
- tests/integration/test_etcd.py
- tests/integration/test_k8s.py
- tests/integration/test_upgrade.py
- tox.ini
Create tests that performs a charm upgrade from k8s edge --> k8s local_path
* eliminates `k8s-worker` leader from checking node readiness on `pre-upgrade-check` action
* `k8s` leader is responsible for checking the whole cluster on `pre-upgrade-check`
* `k8s` checks `kube-system` namespace to ensure all pods are ready during update-status event
* heavy refactor of integration test `conftest.py` to support test configuration by pytest model markings
* `latest/edge` snap is now 1.32, requiring new dependency literals
* increase runner size for amd64 runs
>  [!NOTE]
>  VMs on LXD cannot pull an image for focal that supports cilium.  This PR moves all testing on amd64 therefore to jammy rather than focal.  Focal is still tested on arm64 due to GH ARM64 workers not supporting `/dev/kvm`
> Adjustments to test charm upgrades

- .github/workflows/update-snap-revision.py
- charms/worker/k8s/src/literals.py
- charms/worker/k8s/src/snap.py
- charms/worker/k8s/src/upgrade.py
- charms/worker/k8s/templates/snap_installation.yaml
- charms/worker/k8s/tests/unit/test_snap.py
- charms/worker/k8s/tests/unit/test_upgrade.py
- tests/integration/test_k8s.py
- tests/integration/test_upgrade.py
Pin the revisions based on `snapcraft status k8s`
```
1.32-classic  amd64   stable            v1.32.0       1843        -           -
candidate         v1.32.0       1843        -           -
beta              v1.32.0       1848        -           -
edge              v1.32.0       1848        -           -
arm64   stable            v1.32.0       1844        -           -
candidate         v1.32.0       1849        -           -
beta              v1.32.0       1871        -           -
edge              v1.32.0       1871        -           -
```
* Quite a bit of work here to improve charm upgrades when no suitable source channels exist to upgrade from.
* Removal of the snap installation override feature b/c upgrading all control plane nodes simultaneously doesn't go well
* ensure we run …
> Pin snap_installations to 1.32-classic stables

- .github/workflows/promote-charms.yaml
* multi charm repos like this one have tags per charm and per revision.  such as `k8s-rev123`. 
* The operator-workflows should pass this `tag-prefix` along during the promote job
Depends on 
* https://github.com/canonical/operator-workflows/pull/508
> Provide tag-prefix when promoting charms

- charms/worker/k8s/src/kube_control.py
report over the kube-control relation that images can be found at `rocks.canonical.com/cdk`
> Report the default image registry correctly

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/config/extra_args.py
- charms/worker/k8s/src/containerd.py
- charms/worker/k8s/src/literals.py
Applicable spec: https://github.com/canonical/k8s-operator/issues/238
Bootstraps, and joins nodes using the charm specified containerd base path
The snap config now allows the charm to specify a containerd-base-dir, Lets use that to make sure it doesn't move again.
Updated the k8s library to accommodate new API config
> Bootstrap & join with a fixed containerd-base-dir

- .github/workflows/tiobe-tics-cron.yaml
- charms/worker/k8s/tox.ini
- pyproject.toml
- tox.ini
This commit adds:
- the necessary tox env targets for generating Cobertura coverage report XML format
- a GitHub Workflow which runs the unit tests with coverage enabled, and calls the `TICSServer` to upload the analysis results
Workflow will allow for daily automatic code quality report uploads to Tiobe
N/A
N/A
N/A
> actions: Add Tiobe TICS cron job

- charms/worker/k8s/terraform/variables.tf
- charms/worker/terraform/variables.tf
Don't default the charm channels to `1.30/edge` -- a channel which may be or is already closed. 
Instead, require the tf user to specify a channel
* removes the default channel from the tf modules
> Require tf users to specify a charm channel

- .github/workflows/tiobe-tics-cron.yaml
TICS will try to use pylint and flake8 to analyze the project's code. We need to install them beforehand.
Errors are present in the TICS job:
```
2025-01-16T10:19:31.9465876Z [ERROR 5073] The following error(s) occurred while 'pylint' was running: '/opt/hostedtoolcache/Python/3.12.8/x64/bin/python: No module named pylint
2025-01-16T10:19:42.7100405Z [ERROR 5073] The following error(s) occurred while 'flake8' was running: '/opt/hostedtoolcache/Python/3.12.8/x64/bin/python: No module named flake8
```
N/A
N/A
N/A
> actions: Adds missing dependencies for TICS job

- tests/integration/test_upgrade.py
Handle charm upgrades that might upgrade to a different snap version (ie 1.32.0 -> 1.32.1)
The k8s (control-plane) charm will upgrade first, and signal with a "waiting" status that the workers will need to be updated. 
if the snap revision changes but doesn't bump the patch version, the k8s units will all report "active/idle"
if the snap revision changes but the patch version is different, the leader k8s unit will report "waiting/idle" with a specific message. 
Either of these 2 cases is enough of a gate to allow for upgrades to continue
> Upgrade tests must continue when k8s leader is ready for worker upgrades

- .charmcraft-channel
- .github/workflows/integration_test.yaml
- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
- tests/integration/helpers.py
Upgrade the charmcraft.yaml to use `charmcraft: 3.x`, including platform configurations to target multiple bases and architectures.
To accomodate new binary dependencies like `cryptography` and `pydantic-core`, we are switching over `charmcraft 3.x`. This change allows us to build charms for each architecture/release for both the `k8s` and `k8s-worker` charms.
> Support Multiple Builds-on

- .github/workflows/auto-update-libs-k8s-worker.yaml
- .github/workflows/bot_pr_approval.yaml
- .github/workflows/charm-analysis.yaml
- .github/workflows/comment.yaml
- .github/workflows/comment_contributing.yaml
- .github/workflows/integration_test.yaml
- .github/workflows/load_test.yaml
- .github/workflows/promote-charms.yaml
- .github/workflows/publish-charms.yaml
Pin the `operator-workflows` to the latest SHA instead of main.
> chore: pin `operator-workflows` version

- charms/worker/k8s/terraform/main.tf
- charms/worker/k8s/terraform/variables.tf
The k8s api endpoints are exposed via firewall rules on some substrates through `k8s expose`.  This makes the default to expose the endpoint everywhere by default. 
The expose block can be configured according to the [juju provider TF docs](https://registry.terraform.io/providers/juju/juju/latest/docs/resources/application#nestedblock--expose)
> Expose k8s application config via terraform

- charms/worker/k8s/src/charm.py
When you bootstrap with a `containerd_base_path`, this is not the actual path used for containerd. 
the [k8s snap appends this path to another path](https://github.com/canonical/k8s-snap/blob/ea5f8853818984a7a0d766155b744e846d704653/src/k8s/pkg/k8sd/api/cluster_bootstrap.go#L45-L48), so the charms are still  not writing configs where you'd expect them to.
If we don't bootstrap with it -- we'll get the correct path by "luck" rather than being specific.  Until the snap bug is worked out, this is a workaround
> Dont bootstrap with containerd_base

- tests/integration/conftest.py
- tests/integration/storage.py
- tests/integration/test_ceph.py
- tests/integration/test_openstack.py
* Replace copying manifest files into k8s cp container to run, with using the kubernetes client api
* Hopefully improves tests failures occurring with ceph tests
> Streamline storage tests by using k8s python client

- charms/worker/k8s/templates/snap_installation.yaml
* Set the snap revisions to be fixed which was over-written in #286 
```
1.32-classic  amd64   stable                              v1.32.1          2187        -           -
candidate                           v1.32.1          2187        -           -
beta                                v1.32.1          2187        -           -
edge                                v1.32.1          2187        -           -
arm64   stable                              v1.32.1          2196        -           -
candidate                           v1.32.1          2196        -           -
beta                                v1.32.1          2196        -           -
edge                                v1.32.1          2196        -           -
```
> Manually set from 1.32-classic/stable

- .github/workflows/integration_test.yaml
- .github/workflows/publish-charms.yaml
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/cloud_integration.py
- charms/worker/k8s/src/config/extra_args.py
- charms/worker/k8s/src/events/update_status.py
- charms/worker/k8s/src/kube_control.py
- charms/worker/k8s/src/protocols.py
- charms/worker/k8s/src/reschedule.py
- charms/worker/k8s/src/snap.py
- charms/worker/k8s/src/token_distributor.py
- charms/worker/k8s/src/upgrade.py
- charms/worker/k8s/templates/reschedule.service
- charms/worker/k8s/templates/reschedule.timer
- charms/worker/k8s/tests/unit/test_base.py
- charms/worker/k8s/tests/unit/test_k8sd_api_manager.py
- charms/worker/k8s/tests/unit/test_upgrade.py
- pyproject.toml
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/terraform_setup.py
- tests/integration/test_k8s.py
- tests/integration/test_upgrade.py
- tox.ini
Shrink the number of builds performed on the charms to enable testing from 6 -> 2
* Rather than testing each module with a different set of builds, we can build once per architecture and test with multiple modules
* format and lint with ruff
> Build per arch, test per module

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/mocks.py
- charms/worker/k8s/tests/unit/test_base.py
- charms/worker/k8s/tests/unit/test_k8sd_api_manager.py
- tests/integration/data/test-bundle-openstack.yaml
- tests/integration/test_openstack.py
This PR improves testing around external load balancer endpoint.
The actual integration with an external load balancer is also tested in the current Openstack e2e tests. That's because we've added the relation to the test bundle and in the e2e tests we retrieve the kubeconfig by running the `get-kubeconfig` action. A test for that action is added to make sure it returns the external load balancer endpoint when it's available. So the e2e tests intrinsically test the reachability of the cluster via the external lb endpoint.
> Improve external load balancer endpoint testing

- tests/integration/test_k8s.py
Skip the override integration tests on release branches where the charm isn't build with latest/edge as it's track, but instead it uses a pinned revision
> Skip override snap tests on release branches

- charms/worker/k8s/requirements.txt
- tests/integration/test_k8s.py
`kube-control` is now a Python package, let's pin it to the current working version.
> Pin `kube-control` dependency

- charms/worker/k8s/terraform/versions.tf
- charms/worker/terraform/versions.tf
fix: be less specific on juju version of terraform provider to facilitate deployment with `juju >= 0.14.0`
> Allow Juju tf provider to float past 0.14.0

- .github/workflows/stale-cron.yaml
We're adding a nightly job that automatically closes PRs and issues that have been inactive for 6 months.
It applies an "inactive" label after 5 months and then proceeds to close them after another month.
> CI: Automatically close inactive PRs and issues

- .github/workflows/stale-cron.yaml
We're getting code scanning alerts as the stale job doesn't
contain explicit top-level permissions.
> ci: add top level permissions to the stale job

- .github/workflows/promote-charms.yaml
fix:  charm promotion job needs to be more aware of all the revisions of the charms to promote
The operator-workflows are limited in how it promotes charms.  It can only promote one series/arch revision to the target channel rather than ALL of the revisions in a certain channel.
The workflows do allow one to specify which series/arch they wish to promote, but fails to "validate" that series and arch as it expects a charmcraft 2.x style "bases" header in the charmcraft.yaml rather than the charmcraft 3.x style. 
By switching to the `charming-actions/promote-charm` workflow, it does a better job of just publishing whatever charms are in the the origin channel to the destination channel along with the charm revisions.  It's all wee really need here.
> Bypass operator-workflows promote

- tests/integration/conftest.py
The charm e2e tests take a few parameters, we'll add some more information to the helpstrings:
* charm files
* expected filename format
* expected charm base
* --lxd-containes
* uses lxd containers instead of lxd vms
* will not work with some of the charms and should be avoided
* snap installation resource
* must contain either snap_installation.yaml OR a snap file
> doc: Improve e2e test param documentation

- charms/worker/k8s/pyproject.toml
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/kube_control.py
- charms/worker/k8s/uv.lock
- renovate.json
With the switch UV, dependency updating is halted due to dependabot failing to handle uv.lock files. 
Switch to dep updates by renovate.
> Allow renovate to update uv.lock

- .github/workflows/auto-update-snap-revision.yaml
- .github/workflows/update-snap-revision.py
When snap revisions are released to the stable channels, we always get two PRs, one that ends in a conflict. 
let's just update all the snaps in a single PR for each branch
> Update K8s snap revisions in a single PR rather than multiple prs

- .github/workflows/integration_test.yaml
- tests/integration/conftest.py
- tests/integration/data/test_registries/pod.yaml
- tests/integration/data/test_registries/test-bundle-docker-registry.yaml
- tests/integration/test_registry.py
Adds a test that deploys the docker-registry charm, pulls an image to the registry, tags it with a unique name, and finally tries to pull the image from the registry.
This validates that the charm sets the custom_containerd_config from charm configuration in the right place on the filesystem.
> test: Add integration tests for Kubernetes docker-registry deployment

- charms/worker/k8s/pyproject.toml
- charms/worker/k8s/uv.lock
This PR bumps the `node-base` dependency so that the AZ node labels will be applied according to the following PR:
- https://github.com/charmed-kubernetes/layer-kubernetes-node-base/pull/14
The implementation and tests are done in the `layer-node-base` repo. But writing integration tests for this in the `k8s-operator` repo is impossible (for now). That’s because there’s no way to mock the `JUJU_AVAILABILITY_ZONE` environment variable and currently, the substrate that we’re running the tests on does not provide a `JUJU_AVAILABILITY_ZONE`. Maybe migrating to Openstack, AWS or MAAS will solve this issue. For now, I tested manually and deployed a charm on an AWS cloud with the latest changes and verified that we’re in fact setting the correct node labels. E.g.:
``` …
```
> feat: Bump node-base to apply AZ node labels

- .github/workflows/charm-analysis.yaml
- charms/worker/k8s/pyproject.toml
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/uv.lock
This PR bumps the node-base version to include the AZ node labels according to: https://github.com/charmed-kubernetes/layer-kubernetes-node-base/pull/14
Backports #389
> [Backport 1.32] feat: Bump node-base to apply AZ node labels (#389)

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/src/charm.py
Applicable spec: KU-3276, Resolves issue #437 
Multiple worker applications join the kubernetes cluster via various provider side relations offered by the k8s control-plane charm.  When there are multiple applications present, the charm code on the control plane side cannot use `ops.Model.get_relation` because more than 1 exists. 
Update these scenarios to instead use `ops.relations[<rel>]` which ops guarantees that if no relation exists, it will return an empty list (ie there's no fear of a `KeyError`) so long as the relation is defined in the charm's metadata.
None
None
None
> bug: Address issues where mulitple worker application join a k8s cluster

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/uv.lock
BACKPORT of #438
Applicable spec: KU-3276, Resolves issue #437 
Multiple worker applications join the kubernetes cluster via various provider side relations offered by the k8s control-plane charm.  When there are multiple applications present, the charm code on the control plane side cannot use `ops.Model.get_relation` because more than 1 exists. 
Update these scenarios to instead use `ops.relations[<rel>]` which ops guarantees that if no relation exists, it will return an empty list (ie there's no fear of a `KeyError`) so long as the relation is defined in the charm's metadata.
None
None
None
> Adjust multiple workers related to k8s control-plane

- charms/worker/k8s/charmcraft.yaml
https://documentation.ubuntu.com/canonical-kubernetes/latest/snap/howto/storage/storage/ says:
> Local storage will not survive node removal, so it may not be suitable for certain setups, such as production multi-node clusters.
whereas https://charmhub.io/k8s/configurations#local-storage-enabled  says (for local-storage-enabled):
> This is useful for development and testing purposes. It is not recommended for production use.
The latter is inconsistent and confusing for users.
> fix: change local-storage description

- .github/workflows/download-charm.yaml
- CONTRIBUTING.md
- charms/worker/k8s/terraform/variables.tf
- charms/worker/terraform/variables.tf
Focal is out of support, this PR drops it.
Tiny nit to the docs.
Focal is out of support.
NA
NA
NA
> fix: drop focal

- .github/workflows/promote-charms.yaml
Without access to the `charmcraft.yaml`, the promote-charm action cannot perform metadata inspection from the charm file. 
So, we must checkout
> The promote-charm action needs the checked-out code for access to metadata

- charms/worker/k8s/src/containerd.py
With the quoted arguments in `/var/snap/k8s/common/args/containerd`, the charm needs to unquote them before using them as a path.
previously `/var/snap/k8s/common/args/containerd` contained
```
--config=/etc/containerd/config.toml
```
but now is:
```
--config="/etc/containerd/config.toml"
```
The charm should handle EITHER of these kinds of paths whether quoted or not.  So, we just need to strip any quotes
> Read quoted argument for containerd config path

- charms/worker/k8s/pyproject.toml
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/snap.py
The `k8s` and `k8s-worker` charms now remove installed snaps during charm removal.
Previously, installed snaps were not removed when tearing down the unit. This pull request adds support for the `management` method to ensure snaps are removed only during removal related events in Juju.
Manual testing:
```
❯ juju remove-application k8s
WARNING This command will perform the following actions:
will remove application k8s
- will remove unit k8s/0
Continue [y/N]? y
Every 2.0s: snap list                                                                juju-1c33ed-1: Mon May  5 20:33:31 2025
Name    Version        Rev    Tracking       Publisher    Notes
core20  20230308       1852   latest/stable  canonical**  base
k8s     v1.33.0        3416   latest/edge    canonical**  classic,held
lxd …
```
> fix: remove snaps during removal related events

- charms/worker/k8s/terraform/main.tf
- charms/worker/k8s/terraform/variables.tf
By default, expose to all CIDR ranges
this is equivalent to 
```sh
juju expose k8s
```
See notes from `juju expose --help`
> If no additional options are specified, the command will, by default, allow
access from 0.0.0.0/0 to all ports opened by the application. For example, to
expose all ports opened by apache2, you can run:
> Adjust the default to expose to all cidrs

- charms/worker/k8s/templates/snap_installation.yaml
This PR bumps k8s snap revision to the latest available in candidate.
```
1.33-classic  amd64   stable                                                                       v1.33.1    3592        -           -
candidate                                                                    v1.33.1    3707        -           -
beta                                                                         v1.33.1    3707        -           -
edge                                                                         v1.33.1    3707        -           -
arm64   stable                                                                       v1.33.1    3594        -           -
candidate                                                                    v1.33.1    3705        -           -
beta …
```
> deps: Bump k8s snap revision to candidate

- .github/workflows/auto-update-libs-k8s-worker.yaml
- .github/workflows/bot_pr_approval.yaml
- .github/workflows/charm-analysis.yaml
- .github/workflows/comment.yaml
- .github/workflows/comment_contributing.yaml
- .github/workflows/integration_test.yaml
- .github/workflows/load_test.yaml
- .github/workflows/publish-charms.yaml
* operator-workflows calls internal composite actions only from the main branch
* this makes it impossible to pin the workflows in reality
> Just follow main of operator-workflows

- .github/workflows/publish-charms.yaml
* Don't try to publish the docs or libs from this repo automatically
* https://github.com/canonical/operator-workflows/pull/689
> Skip publishing libs and docs

- charms/worker/k8s/templates/snap_installation.yaml
This PR bumps k8s snap revisions for both AMD and ARM.
```
1.33-classic  amd64   stable                                                                       v1.33.1    3739        -           -
candidate                                                                    v1.33.1    3739        -           -
beta                                                                         v1.33.1    3739        -           -
edge                                                                         v1.33.1    3739        -           -
arm64   stable                                                                       v1.33.1    3745        -           -
candidate                                                                    v1.33.1    3745        -           -
beta …
```
> deps: Bump k8s snap revision

- charms/worker/k8s/src/charm.py
Set the cluster name during bootstrap and use it to bootstrap the cluster.
The original logic for handling the cluster name wasn't working correctly, leading to an empty cluster name during bootstrap. Also, the logic has been improved to prevent a node from being marked as bootstrapped prematurely, using the node list as a safeguard. The PR also includes some improvements to the logging, in order to surface these conditions to the debug log.
> [release-1.32] fix: improve cluster name logic

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/test_base.py
This PR suggests charm actively set the datastore in the bootstrap config file.
> chore: safely set datastore in case of dqlite

- tests/integration/data/test_registries/test-bundle-docker-registry.yaml
- tests/integration/test_registry.py
By default `docker-registry` charm uses `docker.io/registry:2` for its registry image.  Swap this to `ghcr.io/charmed-kubernetes/docker-registry:2` which is just a mirror -- but shouldn't hit rate limit issues with github runners
* also swap out pulling `busybox:latest` from docker.io -- but rather use `rocks.canonical.com/cdk/busybox:1.36` to avoid the same kind of problem
> Use registry image hosted from ghcr.io in test_registry

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/config/arg_files.py
- charms/worker/k8s/src/config/extra_args.py
- charms/worker/k8s/src/literals.py
- tests/unit/config/test_cluster.py
- tests/unit/test_arg_files.py
- tests/unit/test_base.py
Port of https://github.com/canonical/k8s-operator/pull/485
* Support run-time adjustment of the extra-args on the kubernetes services
* Adds `node-ip` as a run-time setting based on the ip addresses bound to the `cluster` endpoint binding
> Apply charm extra-args at runtime

- tests/integration/terraform/default-manifest.yaml
- tests/integration/terraform/openstack-manifest.yaml
- tests/integration/test_openstack.py
- tox.ini
* need to await a juju method to get the pubilc ip address of the openstack instance to compare against the load-balancer address
* this previously produced a warning but not a test failure.
````
tests/integration/test_openstack.py::test_external_load_balancer
/home/ubuntu/actions-runner/_work/sqa-cloud-deployment-pipeline/sqa-cloud-deployment-pipeline/canonicalk8s_test_openstack/tests/integration/test_openstack.py:86: RuntimeWarning: coroutine 'Unit.get_***_address' was never awaited
assert unit.get_***_address() != server_endpoint, "External lb not configured"
Enable tracemalloc to get traceback where the object was allocated.
See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
During handling of the above exception, another exception …
```
> fix: await public ip address to confirm its not the LB ip address

- charms/worker/k8s/src/inspector.py
Backport #586 
* `httpx.ConnectError` is too narrow of an issue to catch for cluster inspection.  It should more use the more broad exception `httpx.HTTPError`.  if anything goes wrong checking the api server, that should be noted as a `ClusterInspectorError`. 
* seen in an integration tests run where the client threw another error, and the charm went into ERROR state.
* For anyone curious (or future reference), here's the hierarchy of HTTPX exceptions: https://www.python-httpx.org/exceptions/
> Catch a broader httpx exception to signal a failure cluster inspection

- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/literals.py
- tests/integration/test_ceph.py
- tests/integration/test_etcd.py
- tests/integration/test_k8s.py
- tests/integration/test_openstack.py
- tests/integration/test_registry.py
* Use configurable timeout for all tests
* Use `ops_test.fast_forward` to speed up tests (by adjusting the update-status rate to 10s)
> fix: Use ops_test.fast_forwards to urge along tests quicker

- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/literals.py
- tests/integration/test_etcd.py
- tests/integration/test_k8s.py
- tests/integration/test_openstack.py
Backport #596 
* Use configurable timeout for all tests
* Use `ops_test.fast_forward` to speed up tests (by adjusting the update-status rate to 10s)
> fix: Use ops_test.fast_forwards to urge along tests quicker (#596)

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/lib/charms/data_platform_libs/v0/data_interfaces.py
- charms/worker/k8s/lib/charms/kubernetes_libs/v0/etcd.py
- charms/worker/k8s/src/certificates.py
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/charmed_etcd.py
- charms/worker/k8s/src/literals.py
- tests/integration/conftest.py
- tests/integration/data/test-bundle-charmed-etcd.yaml
- tests/integration/data/test-bundle-external-certs.yaml
- tests/integration/test_charmed_etcd.py
- tests/unit/test_base.py
Applicable spec: [DA203 - Charmed etcd integration with Canonical K8s](https://docs.google.com/document/d/1kx8kt2S7BZCl4OfHy4nRtjw8dLLA7P6QDtKgLp8kwxo/edit?tab=t.0)
- Add a `etcd-certificates` endpoint
- Add `etcd-client` endpoint
- Implement logic for fetching the etcd client certificate
- Implement logic for communicating with charmed-etcd
Adding charmed-etcd integration.
None
* Added the `CharmedEtcdRequires` class to manage interactions with the Charmed etcd relation, including fetching connection details and managing client credentials. (`charms/worker/k8s/src/charmed_etcd.py`)
* Updated the charm logic to initialize and handle the Charmed etcd relation, including compatibility checks between legacy and Charmed etcd relations. (`charms/worker/k8s/src/charm.py`) …
> [DPE-7667]: Charmed etcd integration 

- charms/worker/k8s/src/snap.py
- charms/worker/k8s/src/upgrade.py
- tests/unit/test_upgrade.py
Applicable spec: KU-182
The snap should now be able to handle restarting its own services, this shouldn't be in the context of the charm.  
This was only ever here in order to workaround some issues with k8s 1.31, and it's masking some bad decisions.  A snap refresh should complete on its own without having to stop/start the k8s services.  It can badly impact quorum on applications which perform raft -- so we just need to not attempt restarts in the charm.
> Do not manage service restarts when performing a snap refresh

- .github/workflows/update-snap-revision.py
- charms/worker/k8s/templates/snap_installation.yaml
Release branch 1.33 should follow the `TRACK`  in the environment of the [auto-update-snap-revision](https://github.com/canonical/k8s-operator/actions/workflows/auto-update-snap-revision.yaml) job
> Release-1.33 branch follows 1.33-classic snaps

- .github/workflows/integration_test.yaml
- CONTRIBUTING.md
- charms/worker/k8s/pyproject.toml
- charms/worker/k8s/uv.lock
- tests/integration/conftest.py
- tests/integration/data/test-bundle-cos.yaml
- tests/integration/helpers.py
- tests/integration/test_cos.py
- tests/integration/test_k8s.py
Move the COS integration tests to an independent module, run only on amd64
* uses https://github.com/aio-libs/async-lru to provide a quick lookup for the cloud arch and cloud substrate
* moves cos tests to be run as  `amd64` only
* cos tests can startup quickly as they only tests on single node k8s
* Run cos tests on every PR (as they are faster than running test_k8s)
> [COS] Integration tests can skip cos tests on arm64

- .github/workflows/integration_test.yaml
- CONTRIBUTING.md
- test_requirements.txt
- tests/integration/conftest.py
- tests/integration/data/test-bundle-cos.yaml
- tests/integration/helpers.py
- tests/integration/test_cos.py
- tests/integration/test_k8s.py
Backport #653 
* Integration tests can skip cos tests on arm64
* Move cos tests to its own module
* Always run cos integration tests
> [Backport 1.32] Integration tests can skip cos tests on arm64

- .github/workflows/integration_test.yaml
- CONTRIBUTING.md
- charms/worker/k8s/pyproject.toml
- charms/worker/k8s/uv.lock
- tests/integration/conftest.py
- tests/integration/data/test-bundle-cos.yaml
- tests/integration/helpers.py
- tests/integration/test_cos.py
- tests/integration/test_k8s.py
Backport #653 
* Integration tests can skip cos tests on arm64
* Move cos tests to its own module
* Always run cos integration tests
> [Backport 1.33] Integration tests can skip cos tests on arm64

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/token_distributor.py
- charms/worker/k8s/tests/unit/test_token_distributor.py
- tests/integration/conftest.py
Backports #649 to release-1.32 branch
----
Fixes issue #648 
* Move get/share/unshare to the TokenManager class to control which relation buckets secret ids appear
* Fix unit name regex for finding unused tokens
* follow 1/stable grafana-agent
> [COS][Backport 1.32] fix: cos-tokens shared in app databag

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/token_distributor.py
- tests/integration/conftest.py
- tests/unit/test_token_distributor.py
Backports #649 to release-1.33 branch
----
Fixes issue #648 
* Move get/share/unshare to the TokenManager class to control which relation buckets secret ids appear
* Fix unit name regex for finding unused tokens
* follow 1/stable grafana-agent
> [COS][Backport 1.33] fix: cos-tokens shared in app databag

- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
Backport 1.33: https://github.com/canonical/k8s-operator/pull/697
k8s and k8s-worker charm documentation on charmhub is incorrect due to old restrictions on the config items `kube-proxy-extra-args` and `kubelet-extra-args`
Update charmcraft.yaml
None
None
None
> docs: kubelet and kube-proxy extra args are runtime configurable
