canonical/k8s-operator

- charms/worker/k8s/src/cos_integration.py
Improve cluster metrics labeling
Many of the metrics were being scraped with labels that didn't allow Grafana to differentiate among instances. Therefore, the metrics were shown as a single unit, instead of rendering different instances. Below is an example of the raw metrics and how they were rendered.
After applying a new set of labels, the metrics are now shown correctly, each labeled with its respective host.
Finally, as Kube State Metrics is a global source of metrics, it does not require labeling with a set of unique metrics. static_configs were introduced as a way to override the default configurations to better define the metrics labels.
> Improve Cluster Metrics Labeling

- charms/worker/k8s/src/charm.py
Add a mechanism to create a suitable configuration in `/etc/environment` for Kubernetes to run in a proxied environment.
Currently, the charms fail to start due to issues with the proxy environment variables. This pull request introduces a mechanism to offload the JUJU_CHARM environment variables to the `/etc/environment` file. This would create a suitable environment in which the snap can infer the values and start correctly.
> Enable `k8s-operator` to run in proxied environments

- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
- charms/worker/k8s/src/charm.py
- charms/worker/k8s/tests/unit/test_base.py
Implements action to retrieve the public kubeconfig file from any k8s unit
> Action to get kubeconfig from k8s control-plane units

- README.md
Updates the badges, adds the charmhub badges
> Update Badges in github readme

- charms/worker/k8s/lib/charms/k8s/v0/k8sd_api_manager.py
Mini PR: Updates from the k8s-snap from https://github.com/canonical/k8s-snap/pull/344.
@addyess
> Move cloud provider field

- .github/.jira_sync_config.yaml
Fixes from comments:
*  https://github.com/canonical/k8s-operator/pull/84/files#diff-eee108ea49e324e51ab610c63c844d18b5b59c80bf21fd9a5b86dbecd8ad1983R12-R14
> Make the jira_sync_config more KU friendly

- .github/workflows/promote-charms.yaml
- .github/workflows/publish-charms.yaml
- .github/workflows/update-snap-revision.py
- .github/workflows/update-snap-revision.yaml
* Create a github cron job which updates release branches with latest available stable revision
* Provider errors when branch doesn't match
* TRACK should be place into the GITHUB_ENV not GITHUB_OUTPUT
> github cron job to update release branch snap_installation.yaml (#83)

- .github/workflows/auto-update-libs-k8s-worker.yaml
- .github/workflows/charm-analysis.yaml
- .github/workflows/comment.yaml
- .github/workflows/integration_test.yaml
- .github/workflows/load_test.yaml
- .github/workflows/promote-charms.yaml
- .github/workflows/publish-charms.yaml
- charms/worker/k8s/src/snap.py
- charms/worker/k8s/templates/snap_installation.yaml
- charms/worker/k8s/tests/unit/test_snap.py
- tests/integration/conftest.py
- tests/integration/test_etcd.py
* pin operator-workflow to a commit
* No long raise_on_blocked, worker charms will be blocked by default until the unit processes the join cluster relation hook
> pin operator-workflow to a commit (#100)

- .github/workflows/update-snap-revision.py
- .github/workflows/update-snap-revision.yaml
- charms/worker/k8s/src/snap.py
- charms/worker/k8s/templates/snap_installation.yaml
main branch doesn't need to pin the snap revision and should pull from latest/edge snaps
> Don't pin to a specific revision in main

- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
Cherry-pick of a147f22dcb116981dcd3118ab484ff6364b24ab7 to main
Resolves issue #113 107
> runs-on noble requires at least juju3.3 and beyond

- charms/worker/k8s/tests/unit/test_k8sd_api_manager.py
- charms/worker/k8s/tests/unit/test_snap.py
- charms/worker/k8s/tests/unit/test_token_distributor.py
- tests/integration/conftest.py
- tests/integration/data/static-proxy-config.yaml
- tests/integration/helpers.py
- tests/integration/test_etcd.py
- tox.ini
Cherry-pick of cea1ec6569cf0f80c6c5003152ca3bf2318cf923 in to the main branch
Also, includes extras to ensure that unit test pass on python 3.12
> Refactor integration tests to be re-entrant (#105)

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/token_distributor.py
Replace `AssertionError` with a newly defined `ReconcileError`.
> Replace AssertionError with ReconcileError

- charms/worker/k8s/src/inspector.py
- charms/worker/k8s/src/literals.py
- charms/worker/k8s/src/upgrade.py
- charms/worker/k8s/tests/unit/test_inspector.py
- charms/worker/k8s/tests/unit/test_upgrade.py
Update the Poetry dependency expression for `k8s-worker` dependencies and refine the verify_nodes status logic.
> Fix Upgrade Check and Literals

- charms/worker/k8s/templates/snap_installation.yaml
- tests/integration/test_k8s.py
- Pinning `amd64` revision to `1698`
- Pinning `arm64` revision to `1701`
> [Release 1.31] Snap Revision Update

- charms/worker/k8s/lib/charms/grafana_agent/v0/cos_agent.py
- charms/worker/k8s/lib/charms/operator_libs_linux/v2/snap.py
Automated action to fetch latest version of charm libraries. The branch of this PR
will be wiped during the next check. Unless you really know what you're doing, you
most likely don't want to push any commits to this branch.
> Update charm libraries

- .github/workflows/charm-analysis.yaml
Use UV to run lint/unit testing against various python versions
> Unit Testing with UV

- charms/worker/k8s/templates/snap_installation.yaml
Manually touch the snap revisions
> [Release 1.32] Manually upgrade the snap revisions

- CONTRIBUTING.md
- README.md
- SECURITY.md
- charms/CONTRIBUTION.md
- charms/worker/README.md
- charms/worker/k8s/README.md
- charms/worker/k8s/terraform/README.md
- charms/worker/terraform/README.md
- docs/releases/stable/index.md
Lint markdown according to markdownlint rules
> Lint with markdownlint

- charms/worker/k8s/src/config/extra_args.py
- charms/worker/k8s/src/literals.py
- tests/integration/conftest.py
- tests/integration/test_k8s.py
Backport of #310  to release-1.32
> containerd base dir is in the oddest nested spot for reasons... (#310)

- charms/worker/k8s/templates/snap_installation.yaml
Updates K8s version for 1.32
* revision=2500
* arch = amd64
> [Release 1.32] Update K8s 1.32 revision on amd64

- charms/worker/k8s/templates/snap_installation.yaml
Updates K8s version for 1.32
* revision=2502
* arch = arm64
> [Release 1.32] Update K8s 1.32 revision on arm64

- charms/worker/k8s/src/charm.py
- charms/worker/k8s/src/pki.py
Migrate from subprocess calls to `cryptography`
> fix: change subprocess calls for cryptography

- renovate.json
Ok, let's only renovate on main
any security issues we'll backport when necessary
> Only run renovate on main

- .github/.jira_sync_config.yaml
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/enhancement_proposal.yml
- .github/workflows/auto-merge-prs.yaml
- .github/workflows/auto-update-snap-revision.yaml
- .github/workflows/charm-analysis.yaml
- .pre-commit-config.yaml
- charms/worker/charmcraft.yaml
- charms/worker/k8s/charmcraft.yaml
- charms/worker/k8s/scripts/rules-patches/core-alert-rules.patch
- charms/worker/k8s/templates/reschedule.service
- charms/worker/k8s/templates/reschedule.timer
- tox.ini
Adds a pre-commit-hook file to the project
* sets up white-space fixing as a pre-commit hook
> White-space pre-commit-hooks

- charms/worker/k8s/templates/snap_installation.yaml
> [Release 1.32] Update K8s revisions ["amd64-2717","arm64-2723"]

- .github/workflows/tiobe-tics-cron.yaml
> fix: use UV in TICS jobs

- charms/worker/k8s/templates/snap_installation.yaml
> [Release 1.32] Update K8s revisions ["amd64-2907","arm64-2908"]

- charms/worker/k8s/templates/snap_installation.yaml
> [Release 1.32] Update K8s revisions ["amd64-3260","arm64-3171"]

- .github/workflows/auto-update-libs-k8s-worker.yaml
- .github/workflows/bot_pr_approval.yaml
- .github/workflows/charm-analysis.yaml
- .github/workflows/comment.yaml
- .github/workflows/comment_contributing.yaml
- .github/workflows/integration_test.yaml
- .github/workflows/load_test.yaml
- .github/workflows/promote-charms.yaml
- .github/workflows/publish-charms.yaml
- charms/worker/k8s/templates/snap_installation.yaml
Updates the snap revision to:
```
1.33-classic  amd64   stable                                    v1.33.0         3372        
arm64   stable                                    v1.33.0         3368        -           
```
Set to stable 1.33 channel.
NA
NA
NA
> release: update revisions release 1.33

- tests/integration/conftest.py
- tests/integration/test_k8s.py
Backport of #307 to release-1.32 branch
> Add configurable timeout to tests

- charms/worker/k8s/templates/snap_installation.yaml
> [Release 1.32] Update K8s revisions ["amd64-3315","arm64-3319"]

- charms/worker/k8s/src/containerd.py
> [Backport 1.32] Read quoted argument for containerd config path

- charms/worker/k8s/src/containerd.py
> [Backport 1.33] Read quoted argument for containerd config path

- charms/worker/k8s/templates/snap_installation.yaml
> [Release 1.32] Update K8s revisions ["amd64-3475","arm64-3449"]

- charms/worker/k8s/templates/snap_installation.yaml
> [Release 1.32] Update K8s revisions ["amd64-3581","arm64-3575"]

- charms/worker/k8s/templates/snap_installation.yaml
Updates K8s revisions for 1.33
* amd64-3592
* arm64-3594
> [Release 1.33] Update K8s revisions ["amd64-3592","arm64-3594"]

- charms/worker/k8s/templates/snap_installation.yaml
This PR bumps k8s snap revisions to the current 1.32-classic/candidate.
```
1.32-classic  amd64   stable                                                                       v1.32.5    3581        -           -
candidate                                                                    v1.32.5    3708        -           -
beta                                                                         v1.32.5    3708        -           -
edge                                                                         v1.32.5    3708        -           -
edge/safe-build-cache-fix                                                    v1.32.5    3614        -           2025-07-04T00:00:00Z
edge/safe-build                                                              v1.32.5    3606        - …
```
> deps: Bump k8s snap revision to candidate

- .github/workflows/publish-charms.yaml
Backports #522 to release-1.32
> [Backport 1.32] Skip publishing libs and docs

- .github/workflows/publish-charms.yaml
Backports #522 to release-1.33
> [Backport 1.33] Skip publishing libs and docs

- charms/worker/k8s/templates/snap_installation.yaml
Update the k8s-snap revision.
We are doing this manually instead of waiting for the automation to get a head start in its testing.
> deps: Bump k8s snap revision. Feature controller fixes

- charms/worker/k8s/src/charm.py
> [!NOTE]  
> Same as #547, this one targets main.
Set the cluster name during bootstrap and use it to bootstrap the cluster.
The original logic for handling the cluster name wasn't working correctly, leading to an empty cluster name during bootstrap. Also, the logic has been improved to prevent a node from being marked as bootstrapped prematurely, using the node list as a safeguard. The PR also includes some improvements to the logging, in order to surface these conditions to the debug log.
> fix: improve cluster name logic

- charms/worker/k8s/templates/snap_installation.yaml
This PR bumps k8s snap revisions to 1.32-classic/edge
```
1.32-classic  amd64   stable                                                                       v1.32.6    3789        -           -
candidate                                                                    v1.32.6    3803        -           -
beta                                                                         v1.32.6    3827        -           -
edge                                                                         v1.32.6    3842        -           -
edge/safe-build-cache-fix                                                    v1.32.5    3614        -           2025-07-04T00:00:00Z
edge/latest-dqlite-fix                                                       v1.32.5    3616        - …
```
> deps: Bump k8s snap revision

- charms/worker/k8s/templates/snap_installation.yaml
Update the `k8s` revision for the `release-1.32` branch.
> [Release 1.32] Update `k8s` revisions [`amd64-3921`, `arm64-3923`]

- .gitignore
- CONTRIBUTING.md
- README.md
- charms/worker/k8s/pyproject.toml
- charms/worker/k8s/uv.lock
- docs/releases/stable/index.md
- tox.ini
Address newly discovered vale errors. 
Thanks https://github.com/canonical/operator-workflows/pull/740
> fix: address vale errors

- charms/worker/k8s/templates/snap_installation.yaml
> [Release 1.32] Update K8s revisions [amd64-4176,arm64-4180]

- charms/worker/k8s/templates/snap_installation.yaml
> [Release 1.32] Update K8s revisions ["amd64-4239","arm64-4242"]

- charms/worker/k8s/templates/snap_installation.yaml
Updates K8s revisions for 1.33
* amd64-4271\n *arm64-4272
> [Release 1.33] Update K8s revisions ["amd64-4271","arm64-4272"]
